
import csv
from pathlib import Path
from models.run_result import RunResult


def write_findings_csv(result: RunResult, output_path: Path) -> None:
    """Function to write the findings to a CSV file.

    Args:
        result (RunResult): RunResults generated by the crosslog pipeline.
        output_path (Path): User provided path where the results will be saved.
    """
    # Write the parent diretory if it does not exist. 
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # This is the normalized finding output
    fieldnames = [
        "rule_id",
        "title",
        "severity",
        "category",
        "mitre_tactic_id",
        "mitre_tactic_name",
        "source",
        "timestamp",
        "host",
        "event_type",
        "message",
        "fields",
    ]

    with output_path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        # CSV writer function for outputing the defined columns
        writer.writeheader()

        for finding in result.findings:
            writer.writerow({
                "rule_id": finding.rule_id,
                "title": finding.title,
                "severity": finding.severity,
                "category": finding.category,
                "mitre_tactic_id": finding.mitre_tactic_id or "",
                "mitre_tactic_name": finding.mitre_tactic_name or "",
                "source": finding.source,
                "timestamp": finding.timestamp,
                "host": finding.host,
                "event_type": finding.event_type,
                "message": finding.message,
                "fields": _flatten_fields(finding.fields),
            })

def _flatten_fields(fields: dict) -> str:
    """Private function for outputting the fields. This is a dictionary object 
    and is different between each finding. The dict will be formatted to one line.

    Args:
        fields (dict): Findings field from the detected results.

    Returns:
        str: One line string separated by ;
    """
    if not fields:
        return ""

    parts = []
    for key in sorted(fields):
        parts.append(f"{key}={fields[key]}")
    return "; ".join(parts)