

from collections import Counter
from pathlib import Path

from models.run_result import RunResult


def write_summary_report(result: RunResult, output_path: Path) -> None:
    """Function generates the summary file.

    Args:
        result (RunResult): RunResults generated by the crosslog pipeline.
        output_path (Path): User provided path where the results will be saved.
    """
    # Variable for holding the lines as an array of strings
    lines: list[str] = []

    # Summary report 
    #TODO could be improved. Could the console and summary writer use the same standard ouput
    lines.append("=== CrossLog Summary Report ===")
    lines.append(f"Files processed:        {result.files_processed}")
    lines.append(f"Normalized events:      {result.total_events()}")
    lines.append(f"Findings:               {result.total_findings()}")
    lines.append(f"Parser errors:          {result.total_parser_errors()}")
    lines.append(f"Normalization errors:   {result.total_normalization_errors()}")
    lines.append(f"Detection errors:       {result.total_detection_errors()}")
    lines.append(f"File errors:            {result.total_file_errors()}")
    lines.append(f"Fatal errors:           {result.fatal_errors}")

    if result.findings:
        severity_counts = Counter(
            (finding.severity or "unknown").lower()
            for finding in result.findings
        )
        lines.append("")
        lines.append("Findings by severity:")
        for severity in ["critical", "high", "medium", "low", "info", "unknown"]:
            count = severity_counts.get(severity, 0)
            if count:
                lines.append(f"  {severity:<8} {count}")

        category_counts = Counter(
            (finding.category or "unknown").lower()
            for finding in result.findings
        )
        lines.append("")
        lines.append("Findings by category:")
        for category, count in sorted(category_counts.items()):
            lines.append(f"  {category:<15} {count}")

        tactic_counts = Counter(
            (finding.mitre_tactic_id or "none", finding.mitre_tactic_name or "unclassified")
            for finding in result.findings
        )
        lines.append("")
        lines.append("Findings by MITRE tactic:")
        for (tactic_id, tactic_name), count in sorted(tactic_counts.items()):
            lines.append(f"  {tactic_id:<8} {tactic_name:<25} {count}")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")